### PR TITLE
refactor: modularize app pipeline

### PR DESCRIPTION
**Pull request by chriscasto**
I changed my mind about making a separate pipeline module.

This PR adds a module for creating CodePipelines and their corresponding resources.  It also modifies the `app-codepipeline` project to use this module, since that's really the best way to test it and verify that it does what it needs to do.  You can see the config used for testing [here](https://github.com/metrotranscom/doorway-config/blob/test/chriscasto/app-codepipeline/chriscasto.tfvars) and the pipeline created by that config [here](https://us-west-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/doorway-chriscasto-bloom-app/view?region=us-west-1).  The infra pipeline does not currently make use of this module.  Time permitting, that will come in a future PR.

I acknowledge that this is a big change, with a lot of files to look through.  The easiest way to test is probably to make a copy of the test var file linked above, make some changes, and deploy under a different workspace.

### CODE REVIEW

**Comment by chriscasto** [comment]
I'm still running things through this pipeline, but I think it should be good to go.  Given how large it is, I want to make sure you have enough time to look it over and test as needed.

**Comment by chriscasto** [comment]
@isaac-looker All the tests have checked out, so please review at your convenience

**Comment by isaac-looker** [comment]
Running plan under a `chris` namespace I'm getting these errors https://gist.github.com/isaac-looker/fd80459857fa6f2b42f35736cf4659f5

**Comment by isaac-looker** [comment]
Can we solve this by listing the ARN resources in a `depends_on` directive within the dependent resources?

**Review by isaac-looker — APPROVED** [review]

**Pull request merged**
