### PR TITLE
Create default tags for AWS provider, add default name local

### LINKED ISSUE #3: Create default tags
Depends on #2

Define a set of tags to be applied to any resources created so resources within the same account can be differentiated.  These are the ones we should start with:

Team
Project
Application
Environment (ie stage in the software development lifecycle)

Note that all of these tags correspond to variables created in a separate issue.

### LINKED ISSUE #4: Add default name local
Depends on #3

We have resources that require a Name tag to identify them properly in the console.  Add a local variable named default_name with a value like "${resource_prefix}-${Environment}-${Application}".  Create another local that includes all previously defined default tags but includes a Name tag with our default value.

### PR DESCRIPTION
**Pull request by glgh**
Fixes #3, fixes #4.

### CODE REVIEW

**Review by chriscasto — CHANGES_REQUESTED** [review]
Did you test this?  The proper naming should be `var.variable_name`, not `tags.variable_name`.

**Review by chriscasto — CHANGES_REQUESTED** [review]
One more change and we should be good.  The Name tag is only supported/useful for some services, so we don't want it by default on all of them.  Take that off and we should be good.  I would also recommend running `terraform fmt` prior to commit just to clean things up, but we haven't talked about that yet so that's on me.

**Comment by glgh** [comment]
> One more change and we should be good. The Name tag is only supported/useful for some services, so we don't want it by default on all of them. Take that off and we should be good. I would also recommend running `terraform fmt` prior to commit just to clean things up, but we haven't talked about that yet so that's on me.

Thanks! PTAL again. Note that I made a new local "default_tags_with_name" as this is how I understand "Create another local that includes all previously defined default tags but includes a Name tag with our default value" in the description of #4, but please let me know if I misunderstood what you mean.

**Review by chriscasto — APPROVED** [review]
lgtm!

**Pull request merged**
