### PR TITLE
Add a new S3 bucket for logging

### LINKED ISSUE #28: Create logging bucket
We'll need a bucket to store log files generated by the ALBs and CloudFront.  Remember to provide a bucket_prefix argument with a short but descriptive name that begins with our resource_prefix var.  Check out the user uploads bucket for inspiration, if needed.

### PR DESCRIPTION
**Pull request by ifranch**
Fixes #28

### CODE REVIEW

**Comment by lisunshiny** [comment]
same as other cl, seems fine to me but will defer to @chriscasto's review (and please run `terraform plan` to test)

**Review by chriscasto — CHANGES_REQUESTED** [review]
Bucket ACLs are an older way of securing access that have been deprecated.  Buckets are locked down by default, so we should leave that out entirely.

**Review by chriscasto — CHANGES_REQUESTED** [review]
Sorry, but I was so preoccupied by the ACL bit that I missed the tags.  Buckets are one of the resources that do not require a Name tag, so it is also safe to omit the tag arg entirely since we have default_tags set.  Last change, I promise!

**Comment by ifranch** [comment]
No problem, thanks for explaining that.

**Review by chriscasto — APPROVED** [review]
lgtm!

**Pull request merged**
